# compose for postgres, pgadmin, and nextjs
services:
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: birthday
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - 5050:80

  birthday:
    build: .
    restart: always
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@postgres:5432/birthday?sslmode=disable
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres:
    driver: local
